#!/usr/bin/env python

Import("env")

# give parent environment access to godot-cpp bindings for types
env.Append(CPPPATH=[env.Dir("src/")])

env_manifold = env.Clone()

env_manifold.Append(CPPPATH=["manifold/include/", "polypartition/src/"])

# tell manifold we want to run operations in series
env_manifold.Append(CPPDEFINES=[("MANIFOLD_PAR", "-1"), ("MANIFOLD_NO_IOSTREAM", "1")])

sources = [
	"manifold/src/boolean_result.cpp",
	"manifold/src/boolean2_diagnostics.cpp",
	"manifold/src/boolean2_offset.cpp",
	"manifold/src/boolean2_predicates.cpp",
	"manifold/src/boolean2_sweep.cpp",
	"manifold/src/boolean2.cpp",
	"manifold/src/boolean3.cpp",
	"manifold/src/constructors.cpp",
	"manifold/src/cross_section.cpp",
	"manifold/src/csg_tree.cpp",
	"manifold/src/edge_op.cpp",
	"manifold/src/face_op.cpp",
	"manifold/src/impl.cpp",
	"manifold/src/manifold.cpp",
	"manifold/src/minkowski.cpp",
	"manifold/src/polygon.cpp",
	"manifold/src/properties.cpp",
	"manifold/src/quickhull.cpp",
	"manifold/src/sdf.cpp",
	"manifold/src/smoothing.cpp",
	"manifold/src/sort.cpp",
	"manifold/src/subdivision.cpp",
	"manifold/src/tree2d.cpp",

	"polypartition/src/polypartition.cpp",

	"src/godot_manifold_register_types.cpp",
	"src/godot_manifold_cross_section.cpp",
	"src/godot_manifold_manifold.cpp",
	"src/godot_manifold_mesh.cpp",
	"src/godot_manifold_meshgl.cpp",
]

manifold_objects = [env_manifold.SharedObject(file) for file in sources]

Return("manifold_objects")
